services:
  sensor-consumer:
    build:
      context: ./sensor-consumer
      dockerfile: Dockerfile
    container_name: sensor-consumer
    ports:
      - "9080:8080" # expose port
    env_file:
      - .env
    networks:
      - sensors-net
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 512M

  sensor-producer:
    build:
      context: ./sensor-producer
      dockerfile: Dockerfile
    container_name: sensor-producer
    ports:
      - "8080:8080" # map to different host port
    env_file:
      - .env
    environment: 
      -SENSOR_TYPE=T
      -SENSOR_ID=1
      -SENSOR_TYPE_NAME=Temperature
    networks:
      - sensors-net
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 256M
networks:
  sensors-net:
    external: true
