
services:
  sensor-consumer:
    build:
      context: ./sensor-consumer
      dockerfile: Dockerfile
    ports:
      - "9001:8080" # expose port
    env_file:
      - .env
    environment:
      - SENSOR_TYPE=T
      - SENSOR_ID=1

  sensor-producer:
    build:
      context: ./sensor-producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # map to different host port
    env_file:
      - .env