services:
  sensor-consumer:
    image: arm64v8/golang:1.24 # Use ARM-compatible image
    build:
      context: ./sensor-consumer
      dockerfile: Dockerfile
    ports:
      - "9080:8080" # expose port
    env_file:
      - .env
    environment:
      - SENSOR_TYPE=T
      - SENSOR_ID=1
      - SENSOR_TYPE_NAME=Temperature
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 512M

  sensor-producer:
    image: arm64v8/golang:1.24 # Use ARM-compatible image
    build:
      context: ./sensor-producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # map to different host port
    env_file:
      - .env
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 256M
