services:
  sensor-consumer:
    build:
      context: ./sensor-consumer
      dockerfile: Dockerfile
    ports:
      - "9080:8080" # expose port
    env_file:
      - .env
    networks:
      - sensors-net
    restart: always
    #replicas: 2

  sensor-producer-temperature-1:
    build:
      context: ./sensor-producer
      dockerfile: Dockerfile
    container_name: sensor-producer-temperature-1
    ports:
      - "8080:8080" # map to different host port
    env_file:
      - .env
    environment:
      - SENSOR_TYPE=T
      - SENSOR_ID=1
      - SENSOR_TYPE_NAME=Temperature
      - MQTT_PRODUCER_CLIENT_ID=sensor-producer-temperature
    networks:
      - sensors-net

  sensor-producer-humidity:
    build:
      context: ./sensor-producer
      dockerfile: Dockerfile
    container_name: sensor-producer-humidity
    ports:
      - "8081:8080" # map to different host port
    env_file:
      - .env
    environment:
      - SENSOR_TYPE=H
      - SENSOR_ID=1
      - SENSOR_TYPE_NAME=Humidity
      - MQTT_PRODUCER_CLIENT_ID=sensor-producer-humidity
    networks:
      - sensors-net

  sensor-producer-temperature-2:
    build:
      context: ./sensor-producer
      dockerfile: Dockerfile
    container_name: sensor-producer-temperature-2
    ports:
      - "8082:8080" # map to different host port
    env_file:
      - .env
    environment:
      - SENSOR_TYPE=T
      - SENSOR_ID=2
      - SENSOR_TYPE_NAME=Temperature
      - MQTT_PRODUCER_CLIENT_ID=sensor-producer-temperature
    networks:
      - sensors-net

  nginx:
    image: nginx:alpine
    ports:
      - "9081:80"  # expose host port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sensors-net
networks:
  sensors-net:
    external: true
