# Build stage
FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy && go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o sensor-consumer main.go

# Run stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/sensor-consumer .
EXPOSE 8080
CMD ["./sensor-consumer"]